### PR TITLE
Allow the style variable name to be customized via Atom's preferences.

### PR DESCRIPTION
**Pull request by zapaiamarce**

### CODE REVIEW

**Comment by zapaiamarce** [comment]
??

**Comment by sabinmarcu** [comment]
apm link it is for now, I guess. Apologies for opening a PR at the same time with virtually the same code.

**Comment by mdmagnusson** [comment]
@ambethia I'm using this branch with an apm link currently and it works great. Are you no longer maintaining this project?

**Comment by ambethia** [comment]
This sounds like a great idea.

**Pull request merged**
